---
 - name: Installation of docker and run the service
   hosts: web
   become: true
   tasks:
     - name: Installing docker
       apt:
         name: docker.io
         state: present
         update_cache: yes
     - name: Running docker
       service: 
         name: docker
         state: started
         enabled: true
     - name: Pull image from private repository
       shell: docker pull flask-app:latest
       args:
         chdir: /home/ubuntu
     - name: Run the flask container
       shell: docker run -d -p 5000:5000 --name flask-app flask-app:latest
...
