---
 - name: Installation of docker and run the service
   hosts: web
   become: true
   tasks:
     - name: Installing docker
       apt:
         name: docker.io
         state: present
         update_cache: yes
     - name: Running docker
       service: 
         name: docker
         state: started
         enabled: true
    
...
